#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the FluentMappingGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Telerik.OpenAccess.Metadata.Relational;

namespace FurnitureSystem.MySql.Data
{

	public partial class FurnitureSystemMySqlDbContextMetadataSource : FluentMetadataSource
	{

        protected override IList<MappingConfiguration> PrepareMapping()
        {
            List<MappingConfiguration> configurations = new List<MappingConfiguration>();

            var manufacturerMapping = new MappingConfiguration<Manufacturer>();
            manufacturerMapping.MapType(manufacturer => new
            {
                ID = manufacturer.Id,
                Name = manufacturer.Name,
                Section = manufacturer.Sections
            }).ToTable("Manufacturer");
            manufacturerMapping.HasProperty(c => c.Id).IsIdentity();

            configurations.Add(manufacturerMapping);

            var shopMapping = new MappingConfiguration<Shop>();
            shopMapping.MapType(shop => new
            {
                ID = shop.Id,
                Name = shop.Name,
                Location = shop.Location,
                FurniturePieces = shop.FurniturePieces
            }).ToTable("Manufacturer");
            shopMapping.HasProperty(c => c.Id).IsIdentity();

            configurations.Add(shopMapping);

            var furniturePieceMapping = new MappingConfiguration<FurniturePiece>();
            furniturePieceMapping.MapType(furniturePiece => new
            {
                ID = furniturePiece.Id,
                Name = furniturePiece.Name,
                Price = furniturePiece.Price,
                Colour = furniturePiece.Colours,
                Section = furniturePiece.Section,
                Shop = furniturePiece.Shops
            }).ToTable("Manufacturer");
            furniturePieceMapping.HasProperty(c => c.Id).IsIdentity();

            configurations.Add(furniturePieceMapping);
            return configurations;
        }
		
		protected override void SetContainerSettings(MetadataContainer container)
		{
			container.Name = "FurnitureSystemMySqlDbContext";
			container.DefaultNamespace = "FurnitureSystem.MySql.Data";
			container.NameGenerator.SourceStrategy = Telerik.OpenAccess.Metadata.NamingSourceStrategy.Property;
			container.NameGenerator.RemoveCamelCase = false;
		}
	}
}
#pragma warning restore 1591
