#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using FurnitureSystem.MySqlDbContext;

namespace FurnitureSystem.MySqlDbContext	
{
	public partial class FurnitureSystemEntities : OpenAccessContext, IFurnitureSystemEntitiesUnitOfWork
	{
        private static string connectionStringName = @"FurnitureSystemConnection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = new FurnitureSystemEntitiesMetadataSource();
		
		public FurnitureSystemEntities()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public FurnitureSystemEntities(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public FurnitureSystemEntities(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public FurnitureSystemEntities(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public FurnitureSystemEntities(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<Shop> Shops 
		{
			get
			{
				return this.GetAll<Shop>();
			}
		}
		
		public IQueryable<Section> Sections 
		{
			get
			{
				return this.GetAll<Section>();
			}
		}
		
		public IQueryable<Price> Prices 
		{
			get
			{
				return this.GetAll<Price>();
			}
		}
		
		public IQueryable<Manufacturer> Manufacturers 
		{
			get
			{
				return this.GetAll<Manufacturer>();
			}
		}
		
		public IQueryable<Location> Locations 
		{
			get
			{
				return this.GetAll<Location>();
			}
		}
		
		public IQueryable<FurniturePiece> FurniturePieces 
		{
			get
			{
				return this.GetAll<FurniturePiece>();
			}
		}
		
		public IQueryable<Colour> Colours 
		{
			get
			{
				return this.GetAll<Colour>();
			}
		}
		
		public IQueryable<__MigrationHistory> __MigrationHistories 
		{
			get
			{
				return this.GetAll<__MigrationHistory>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MsSql";
			backend.ProviderName = "System.Data.SqlClient";
		
			CustomizeBackendConfiguration(ref backend);
		
			return backend;
		}
		
		/// <summary>
		/// Allows you to customize the BackendConfiguration of FurnitureSystemEntities.
		/// </summary>
		/// <param name="config">The BackendConfiguration of FurnitureSystemEntities.</param>
		static partial void CustomizeBackendConfiguration(ref BackendConfiguration config);
		
	}
	
	public interface IFurnitureSystemEntitiesUnitOfWork : IUnitOfWork
	{
		IQueryable<Shop> Shops
		{
			get;
		}
		IQueryable<Section> Sections
		{
			get;
		}
		IQueryable<Price> Prices
		{
			get;
		}
		IQueryable<Manufacturer> Manufacturers
		{
			get;
		}
		IQueryable<Location> Locations
		{
			get;
		}
		IQueryable<FurniturePiece> FurniturePieces
		{
			get;
		}
		IQueryable<Colour> Colours
		{
			get;
		}
		IQueryable<__MigrationHistory> __MigrationHistories
		{
			get;
		}
	}
}
#pragma warning restore 1591
