#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using FurnitureSystem.MySqlDbContext;

namespace FurnitureSystem.MySqlDbContext	
{
	public partial class FurniturePiece
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _name;
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		
		private int _type;
		public virtual int Type
		{
			get
			{
				return this._type;
			}
			set
			{
				this._type = value;
			}
		}
		
		private int _material;
		public virtual int Material
		{
			get
			{
				return this._material;
			}
			set
			{
				this._material = value;
			}
		}
		
		private int _sectionId;
		public virtual int SectionId
		{
			get
			{
				return this._sectionId;
			}
			set
			{
				this._sectionId = value;
			}
		}
		
		private int _priceId;
		public virtual int PriceId
		{
			get
			{
				return this._priceId;
			}
			set
			{
				this._priceId = value;
			}
		}
		
		private Price _price;
		public virtual Price Price
		{
			get
			{
				return this._price;
			}
			set
			{
				this._price = value;
			}
		}
		
		private Section _section;
		public virtual Section Section
		{
			get
			{
				return this._section;
			}
			set
			{
				this._section = value;
			}
		}
		
		private IList<Shop> _shops = new List<Shop>();
		public virtual IList<Shop> Shops
		{
			get
			{
				return this._shops;
			}
		}
		
		private IList<Colour> _colours = new List<Colour>();
		public virtual IList<Colour> Colours
		{
			get
			{
				return this._colours;
			}
		}
		
	}
}
#pragma warning restore 1591
