#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using FurnitureSystem.MySqlDbContext;

namespace FurnitureSystem.MySqlDbContext	
{
	public partial class Location
	{
		private int _shopId;
		public virtual int ShopId
		{
			get
			{
				return this._shopId;
			}
			set
			{
				this._shopId = value;
			}
		}
		
		private string _country;
		public virtual string Country
		{
			get
			{
				return this._country;
			}
			set
			{
				this._country = value;
			}
		}
		
		private string _city;
		public virtual string City
		{
			get
			{
				return this._city;
			}
			set
			{
				this._city = value;
			}
		}
		
		private string _street;
		public virtual string Street
		{
			get
			{
				return this._street;
			}
			set
			{
				this._street = value;
			}
		}
		
		private int _number;
		public virtual int Number
		{
			get
			{
				return this._number;
			}
			set
			{
				this._number = value;
			}
		}
		
		private Shop _shop;
		public virtual Shop Shop
		{
			get
			{
				return this._shop;
			}
			set
			{
				this._shop = value;
			}
		}
		
	}
}
#pragma warning restore 1591
