#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using FurnitureSystem.MySqlDbContext;

namespace FurnitureSystem.MySqlDbContext	
{
	public partial class Section
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _name;
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		
		private int _manufacturerId;
		public virtual int ManufacturerId
		{
			get
			{
				return this._manufacturerId;
			}
			set
			{
				this._manufacturerId = value;
			}
		}
		
		private Manufacturer _manufacturer;
		public virtual Manufacturer Manufacturer
		{
			get
			{
				return this._manufacturer;
			}
			set
			{
				this._manufacturer = value;
			}
		}
		
		private IList<FurniturePiece> _furniturePieces = new List<FurniturePiece>();
		public virtual IList<FurniturePiece> FurniturePieces
		{
			get
			{
				return this._furniturePieces;
			}
		}
		
	}
}
#pragma warning restore 1591
