#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the FluentMappingGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Telerik.OpenAccess.Metadata.Relational;

namespace DbContext
{

	public partial class FluentModel1MetadataSource : FluentMetadataSource
	{

        protected override IList<MappingConfiguration> PrepareMapping()
        {
            List<MappingConfiguration> configurations = new List<MappingConfiguration>();

            var customerMapping = new MappingConfiguration<Manufacturer>();
            customerMapping.MapType(customer => new
            {
                ID = customer.Id,
                Name = customer.Name
            }).ToTable("Manufacturer");
            customerMapping.HasProperty(c => c.Id).IsIdentity();

            configurations.Add(customerMapping);

            return configurations;
        }
		
		protected override void SetContainerSettings(MetadataContainer container)
		{
			container.Name = "FluentModel1";
			container.DefaultNamespace = "DbContext";
			container.NameGenerator.SourceStrategy = Telerik.OpenAccess.Metadata.NamingSourceStrategy.Property;
			container.NameGenerator.RemoveCamelCase = false;
		}
	}
}
#pragma warning restore 1591
